import 'dart:convert';
import 'package:Covid19/model/model1.dart';
import 'package:http/http.dart';

class Network{

  Future<Autogenerated> getModel() async{
    String url = "https://github.com/sab99r/Indian-States-And-Districts/blob/master/states-and-districts.json";

    final response = await get(Uri.decodeFull(url));

    if(response.statusCode == 200){

      return Autogenerated.fromJson(json.decode(response.body));
    }
    else{
      print('Failed Loading');
    }

  }  
}